/*
CREAR LA SIGUIENTE TABLA

NOTA ANTES DE HACER UN ADD O PUSH DEBES DE IR A GIT --> INICIAR PARA INICIAR EL REPOSITORIO LOCALMENTE DESPUES TENDRAS QUE
IRTE A EQUIPO--> VERSIONES DEL MENU PRINCIPAL, ALLI SE ABRE LA VENTANA VERSIONES EN LA PARTE INFERIOR IZQUIERDA, SOLAMENTE
TIENES QUE IRERTE A LA OPCION "REMOTOS SELECCIONAR ORIGEN Y RECUPERAR Y LISTO, YA PUEDES HACER ADD Y COMMITS Y TODO LO QUE
QUIERAS HACER A TU MUGROSO GITHUB
*/

CREATE TABLE EMPLEADO (ID_EMPLEADO INTEGER, NOMBRE_EMPLEADO VARCHAR(30),  SUELDO_BASE FLOAT, FECHA_CONTRATACION DATE,
CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);