/*
CREAR LA SIGUIENTE TABLA

NOTA ANTES DE HACER UN ADD O PUSH DEBES DE IR A GIT --> INICIAR PARA INICIAR EL REPOSITORIO LOCALMENTE DESPUES TENDRAS QUE
IRTE A EQUIPO--> VERSIONES DEL MENU PRINCIPAL, ALLI SE ABRE LA VENTANA VERSIONES EN LA PARTE INFERIOR IZQUIERDA, SOLAMENTE
TIENES QUE IRERTE A LA OPCION "REMOTOS SELECCIONAR ORIGEN Y RECUPERAR Y LISTO, YA PUEDES HACER ADD Y COMMITS Y TODO LO QUE
QUIERAS HACER A TU MUGROSO GITHUB
*/

CREATE TABLE EMPLEADO (ID_EMPLEADO INTEGER, NOMBRE_EMPLEADO VARCHAR(30),  SUELDO_BASE FLOAT, FECHA_CONTRATACION DATE,
CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);
--ACTIVAMOS LA CONSOLA DE ORACLE, SE INVOCA SOLALEMNET UNA VEZ POR SESION DE SCL DEVELOPER
SET SERVEROUTPUT ON;

/*
VAMOS A GENERAR UN BLOQUE PL SQL
*/
DECLARE
MY_FECHA DATE;
BEGIN

/*
USO DE LA FUNCION TO_DATE PARA TRANSFORMAR FECHAS:
EJEMPLO TO_DATE('01-OCT-1986', 'DD-MON-YYYY')
*/
MY_FECHA:=TO_DATE('25-MAY-2016','DD-MON-YYYY');
INSERT INTO EMPLEADO(ID_EMPLEADO, NOMBRE_EMPLEADO,FECHA_CONTRATACION) 
VALUES(1,'CHANA',MY_FECHA);
DBMS_OUTPUT.PUT_LINE('REGISTRO GUARDADO CON EXITO');

EXCEPTION
WHEN OTHERS
THEN
DBMS_OUTPUT.PUT_LINE('NO SE PUDO TONTO(A)');
END;
/
SELECT * FROM EMPLEADO;

