--Creamos la tabla pelicula
CREATE TABLE PELICULA(ID_PELICULA INTEGER,
TITULO VARCHAR2(40), SINOPSIS VARCHAR2(400),
CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
);
--SECUENCIA
CREATE SEQUENCE SEC_PELICULA
START WITH 1
INCREMENT BY 1
NOMAXVALUE;


--PROCEDIMIENTO
CREATE OR REPLACE PROCEDURE GUARDAR_PELICULA(MY_ID_PELICULA OUT INTEGER,
MY_TITULO IN VARCHAR2, MY_SINOPSIS IN VARCHAR2) AS
BEGIN
SELECT SEC_PELICULA.NEXTVAL INTO MY_ID_PELICULA FROM DUAL;
INSERT INTO PELICULA VALUES(MY_ID_PELICULA, MY_TITULO, MY_SINOPSIS);
END;
/

